### ISSUE TITLE
Failed to run default vs example

### ISSUE THREAD

**Issue by KBraham** [Gladdy/EasyOpenCL#1]
Running the example as given in the vs2013 directory results in the following error:

```
Error: You passed vectors with different lengths to the framework
```

Shouldn't the third vector be equally long as the second vector, 5 elements in total?

```
    std::vector<int> in1(5, 5);
    std::vector<int> in2{ 123, 213, 121, 1231, 123 };
    std::vector<int> in3;

    for (int i = 0; i <= 5; i++) {
        in3.push_back(i); // {0, 1, 2, 3, 4, 5}
    }
```

Running the example with a length 5 outputs a result for the arithmetic kernel.

**Comment by Gladdy** [comment]
Yes, of course. You're completely right. I have changed the code accordingly.
